# app params

channel_names: ["CAM_FRONT"] #, "CAM_FRONT_LEFT", "CAM_FRONT_RIGHT", "CAM_BACK", "CAM_BACK_LEFT", "CAM_BACK_RIGHT"]

n_similar_images: 40 #define the number of simlar images to retrieve for each image

query_image_name: "n008-2018-08-27-11-48-51-0400__CAM_FRONT__1535385093162404.jpg"
